# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.java.home=C:\\Users\\xdshe\\.gradle\\jdks\\eclipse_adoptium-17-amd64-windows\\jdk-17.0.19+10
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.code.style=official
kotlin.incremental=true
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=35
android.enableJetpackComposeCompilerMetrics=false
android.nonTransitiveRClass=true
android.nonFinalResIds=false
